import { buildMetadata } from "@/lib/metadata";

export const metadata = buildMetadata({
  title: "Front Yard Design | Orlano Gardens",
  description: "Create a stronger entrance, more deliberate foundation planting and a front yard that respects the architecture, access and long-term scale.",
  path: "/services/front-yard-design"
});

const structuredData = {
  "@context":"https://schema.org",
  "@type":"Organization",
  "name":"Orlano Gardens",
  "url":"https://orlanogardens.com/services/front-yard-design",
  "email":"orlanogardens@gmail.com",
  "sameAs":["https://orlanogardens.etsy.com/","https://www.instagram.com/orlanogardens","https://www.facebook.com/orlanogardens"],
  "description":"Remote digital outdoor design created from client-supplied property photos."
};

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
      <main id="main-content">
      <section className="hero"><div className="container hero__grid"><div><div className="eyebrow">Service / Front Yard Design</div><h1>Give the property a clearer welcome.</h1><p className="lead">Create a stronger entrance, more deliberate foundation planting and a front yard that respects the architecture, access and long-term scale.</p><div className="btn-row"><a className="btn btn--primary" href="/get-custom-design">Get Your Custom Design</a><a className="btn btn--outline" href="/pricing">View Packages</a></div><p className="service-clarifier">Remote digital design only. Physical landscaping, site visits and installation are not included.</p></div><div className="hero__visual"><span className="image-label">Digital Design Concept</span><img className="hero__image" src="/assets/images/front-yard-before-after.webp" alt="Front yard before and custom digital design concept" /><div className="hero__caption"><strong>See the decision before the expense.</strong><span>The concept uses the submitted view as the design starting point.</span></div></div></div></section>
      <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">What this service can solve</div><h2>Design the decisions that control the space.</h2></div><p>The service is built around a real outdoor problem, not a pre-made style.</p></div><div className="grid grid--4"><article className="card" data-reveal=""><span className="card__number">01</span><h3>Foundation beds</h3><p>Build planting layers without covering windows, vents or architectural details.</p></article><article className="card" data-reveal=""><span className="card__number">02</span><h3>Entrances</h3><p>Strengthen the route to the door with controlled hierarchy and material rhythm.</p></article><article className="card" data-reveal=""><span className="card__number">03</span><h3>Driveway edges</h3><p>Resolve awkward open ground while protecting vehicle and walking clearance.</p></article><article className="card" data-reveal=""><span className="card__number">04</span><h3>Tree + lawn islands</h3><p>Make isolated features read as part of one composition rather than leftover beds.</p></article></div></div></section>
      <section className="section section--dark"><div className="container split"><div><div className="eyebrow eyebrow--gold">Start with the constraints</div><h2>The right concept protects what must keep working.</h2><p>A visually attractive image is worthless if it blocks windows, narrows circulation, ignores drainage or relies on plants that cannot fit at maturity.</p><ul className="check-list"><li>Mature plant height and width</li><li>Window, meter and path clearance</li><li>Sun, drainage and local climate</li><li>Maintenance tolerance and material limits</li></ul></div><div className="card"><div className="eyebrow">Common failure points</div><h3>What the design must correct</h3><ul className="plain-list"><li>A flat row of similar shrubs</li><li>Plants already crowding windows</li><li>An entrance with no visual hierarchy</li><li>Too many unrelated stone or mulch colors</li></ul></div></div></section>
      <section className="section section--ivory"><div className="container"><div className="section-heading"><div><div className="eyebrow">Original space to direction</div><h2>The supplied photo stays visible in the logic.</h2></div><p>Every visualization must remain labeled so it cannot be mistaken for completed physical installation.</p></div><div className="comparison-card"><img src="/assets/images/front-yard-before-after.webp" alt="Front yard before and custom digital design concept" loading="lazy" /><div className="comparison-card__labels"><span>Original space</span><span>Digital Design Concept</span></div><div className="comparison-card__body"><h3>Site-faithful comparison</h3><p>Architecture, property boundaries and fixed features remain the reference for the proposed direction.</p></div></div></div></section>
      <section className="section"><div className="container split"><div className="image-frame"><span className="image-label">Practical handoff</span><img src="/assets/images/front-yard-deliverables.webp" alt="Example plant, material and layout handoff" loading="lazy" /><p className="image-caption">Example presentation only. Final contents depend on the purchased scope and selected direction.</p></div><div><div className="eyebrow">What you receive</div><h2>More than a single pretty image.</h2><ul className="check-list"><li>Custom visual concepts created from the submitted photographs</li><li>Plant and material direction appropriate to the design intent</li><li>Layout and placement guidance for the selected concept</li><li>Tool, setup and basic care notes</li><li>One focused revision after concept selection</li></ul></div></div></section>
      <section className="section section--sage"><div className="container"><div className="section-heading"><div><div className="eyebrow">The service flow</div><h2>Four decisions. One clear handoff.</h2></div><p>Complete inputs are required before the delivery window begins.</p></div><div className="process-line"><div className="process-step"><span className="process-step__number">01</span><h3>Share photos</h3><p>Wide views, side angles, a slow walkthrough, location and measurements.</p></div><div className="process-step"><span className="process-step__number">02</span><h3>Confirm scope</h3><p>The correct service and package are agreed before Etsy checkout.</p></div><div className="process-step"><span className="process-step__number">03</span><h3>Compare concepts</h3><p>Review the custom directions and select one for refinement.</p></div><div className="process-step"><span className="process-step__number">04</span><h3>Use the plan</h3><p>Receive the final visual and practical guidance in 3–5 working days after complete inputs.</p></div></div></div></section>
      <section className="section"><div className="container split"><div><div className="eyebrow">Likely package scope</div><h2>Price follows complexity.</h2><p className="lead">Small focused front beds may fit $29 or $49. A complete medium front yard generally begins at $89 after photo review.</p><p>Do not buy a package from this sentence alone. Send the complete area first so the property can be reviewed.</p><a className="btn btn--primary" href="/get-custom-design">Confirm My Scope</a></div><div className="card card--gold"><h3>Implementation remains local.</h3><p>Use the design yourself or share it with a local landscaper. Verify plant suitability, utilities, drainage, product instructions, permits and structural requirements before physical work.</p></div></div></section>
      <section className="cta-band"><div className="container cta-band__inner"><div><div className="eyebrow eyebrow--gold">Ready when the space is</div><h2>Start with the actual space.</h2><p>Share clear photos and priorities so the correct scope can be confirmed before Etsy checkout.</p></div><a className="btn btn--gold" href="/get-custom-design">Get Your Custom Design</a></div></section>
      </main>
    </>
  );
}
