import {NextResponse} from "next/server";
import {getDb} from "@/lib/mongodb";
import {requireAdmin} from "@/lib/admin-session";
import {guides} from "@/lib/guides";
import {legacyToArticle} from "@/lib/article-normalize";
export const dynamic="force-dynamic";
const legacyArticle=(g,index)=>({id:`legacy:${g.slug}`,...legacyToArticle(g,index),legacy:true});
export async function GET(){try{await requireAdmin();const db=await getDb();const saved=await db.collection("articles").find({}).sort({featured:-1,updatedAt:-1}).toArray();const savedSlugs=new Set(saved.map(x=>x.slug));return NextResponse.json([...saved.map(({_id,...x})=>({id:String(_id),...x})),...guides.filter(g=>!savedSlugs.has(g.slug)).map((g,i)=>legacyArticle(g,i))]);}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
export async function POST(req){try{const admin=await requireAdmin();const body=await req.json();const now=new Date();const article={...body,title:String(body.title||"Untitled article").trim(),slug:String(body.slug||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),author:body.author||"Orlano Gardens",status:["draft","published","scheduled"].includes(body.status)?body.status:"draft",featured:Boolean(body.featured),blocks:Array.isArray(body.blocks)?body.blocks:[],createdAt:now,updatedAt:now,updatedBy:admin.email,publishAt:body.publishAt?new Date(body.publishAt):null};if(!article.slug)return NextResponse.json({error:"Slug is required"},{status:400});const db=await getDb();if(await db.collection("articles").findOne({slug:article.slug}))return NextResponse.json({error:"This slug is already in use"},{status:409});if(article.featured)await db.collection("articles").updateMany({},{$set:{featured:false}});const result=await db.collection("articles").insertOne(article);return NextResponse.json({ok:true,id:String(result.insertedId)});}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
