import {NextResponse} from "next/server";
import {ObjectId} from "mongodb";
import {getDb} from "@/lib/mongodb";
import {requireAdmin} from "@/lib/admin-session";
import {getContentType} from "@/lib/content-types";
import {seedsFor} from "@/lib/cms-seeds";
export const dynamic="force-dynamic";
export async function GET(_req,{params}){try{const admin=await requireAdmin();const {type}=await params;if(!getContentType(type))return NextResponse.json({error:"Unknown content type"},{status:404});const db=await getDb();let rows=await db.collection("cms_records").find({type}).sort({order:1,updatedAt:-1}).toArray();const migrationKey=`initial-content:${type}`;const migrated=await db.collection("cms_migrations").findOne({key:migrationKey});if(!migrated){const now=new Date();const seeds=rows.length?[]:seedsFor(type).map(x=>({...x,type,createdAt:now,updatedAt:now,updatedBy:admin.email}));if(seeds.length)await db.collection("cms_records").insertMany(seeds);await db.collection("cms_migrations").updateOne({key:migrationKey},{$setOnInsert:{key:migrationKey,createdAt:now}},{upsert:true});rows=await db.collection("cms_records").find({type}).sort({order:1,updatedAt:-1}).toArray();}return NextResponse.json(rows.map(({_id,...x})=>({id:String(_id),...x})));}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
export async function POST(req,{params}){try{const admin=await requireAdmin();const {type}=await params;if(!getContentType(type))return NextResponse.json({error:"Unknown content type"},{status:404});const body=await req.json();const now=new Date();const db=await getDb();if(body.id){const id=new ObjectId(body.id);const current=await db.collection("cms_records").findOne({_id:id});if(current)await db.collection("cms_revisions").insertOne({recordId:id,type,snapshot:current,createdAt:now,createdBy:admin.email});const data={...body.data,type,updatedAt:now,updatedBy:admin.email};await db.collection("cms_records").updateOne({_id:id},{$set:data});return NextResponse.json({ok:true,id:body.id});}const max=await db.collection("cms_records").find({type}).sort({order:-1}).limit(1).next();const result=await db.collection("cms_records").insertOne({...body.data,type,order:(max?.order||0)+1,createdAt:now,updatedAt:now,updatedBy:admin.email});return NextResponse.json({ok:true,id:String(result.insertedId)});}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
export async function DELETE(req,{params}){try{await requireAdmin();const {type}=await params;if(!getContentType(type))return NextResponse.json({error:"Unknown content type"},{status:404});const {id}=await req.json();const db=await getDb();await db.collection("cms_records").deleteOne({_id:new ObjectId(id),type});return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
