import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { getDb } from "@/lib/mongodb";
import { verifySession } from "@/lib/auth";
import {ObjectId} from "mongodb";
export const runtime="nodejs";
export async function GET(){try{const token=(await cookies()).get("orlano_admin_session")?.value;if(!token)return NextResponse.json({error:"Unauthorized"},{status:401});verifySession(token);const db=await getDb();const items=await db.collection("media").find({},{projection:{data:0}}).sort({createdAt:-1}).toArray();return NextResponse.json(items.map(x=>({id:String(x._id),name:x.name,type:x.type,size:x.size,createdAt:x.createdAt,url:`/api/media/${x._id}`})));}catch(error){return NextResponse.json({error:error.message},{status:500});}}
export async function POST(request){try{const token=(await cookies()).get("orlano_admin_session")?.value;if(!token)return NextResponse.json({error:"Unauthorized"},{status:401});verifySession(token);const form=await request.formData();const file=form.get("file");if(!file||typeof file==="string")return NextResponse.json({error:"Select an image"},{status:400});const allowed=new Set(["image/png","image/jpeg","image/webp","image/gif","image/avif"]);if(!allowed.has(file.type))return NextResponse.json({error:"Use PNG, JPEG, WebP, GIF or AVIF"},{status:400});if(file.size>8*1024*1024)return NextResponse.json({error:"Image must be under 8 MB"},{status:400});const db=await getDb();const result=await db.collection("media").insertOne({name:file.name,type:file.type,size:file.size,data:Buffer.from(await file.arrayBuffer()),createdAt:new Date()});return NextResponse.json({ok:true,url:`/api/media/${result.insertedId}`});}catch(error){return NextResponse.json({error:error.message},{status:500});}}
export async function DELETE(request){try{const token=(await cookies()).get("orlano_admin_session")?.value;if(!token)return NextResponse.json({error:"Unauthorized"},{status:401});verifySession(token);const {id}=await request.json();const db=await getDb();await db.collection("media").deleteOne({_id:new ObjectId(id)});return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error.message},{status:500});}}
