export const contentTypes={
pages:{title:"Pages",description:"Manage primary page introductions and visibility.",fields:[["name","Page name","text",true],["path","Page path","text",true],["eyebrow","Eyebrow","text"],["heading","Heading","text"],["body","Description","textarea"],["image","Image","image"],["alt","Image alt text","text"],["visible","Visible","boolean"]]},
services:{title:"Services & Pricing",description:"Manage services, package prices and checkout links.",fields:[["title","Service or package name","text",true],["price","Price","text"],["description","Description","textarea"],["deliverables","Deliverables, one per line","textarea"],["checkoutUrl","Checkout URL","url"],["image","Image","image"],["visible","Visible","boolean"]]},
portfolio:{title:"Portfolio",description:"Manage projects, locations and before-and-after work.",fields:[["title","Project title","text",true],["location","Location","text"],["category","Category","text"],["description","Description","textarea"],["beforeImage","Before image","image"],["afterImage","After image","image"],["visible","Visible","boolean"]]},
products:{title:"Ready-to-Use Products",description:"Manage premade designs and product galleries.",fields:[["title","Product title","text",true],["slug","Slug","text",true],["price","Price","text"],["description","Description","textarea"],["image","Main image","image"],["etsyUrl","Etsy URL","url"],["visible","Visible","boolean"]]},
reviews:{title:"Client Reviews",description:"Manage verified feedback and ratings.",fields:[["name","Client name","text",true],["quote","Review","textarea",true],["rating","Rating","number"],["source","Source","text"],["verified","Verified","boolean"],["visible","Visible","boolean"]]},
faqs:{title:"FAQs",description:"Manage questions, answers and categories.",fields:[["question","Question","text",true],["answer","Answer","textarea",true],["category","Category","text"],["visible","Visible","boolean"]]},
legal:{title:"Legal Pages",description:"Manage legal page titles and complete content.",fields:[["page","Policy page","select",true,["Privacy Policy","Terms and Conditions","Cookie Policy","Disclaimer","Accessibility"]],["title","Page title","text",true],["body","Complete policy content","textarea",true],["effectiveDate","Effective date","date"],["visible","Visible","boolean"]]},
navigation:{title:"Navigation & Footer",description:"Manage header, footer, social and CTA links.",fields:[["label","Label","text",true],["url","Destination URL","text",true],["location","Location","select",true,["Header","Services menu","Footer services","Footer explore","Footer policies","Social","CTA"]],["visible","Visible","boolean"]]},
settings:{title:"SEO & Site Settings",description:"Manage global website values and metadata.",fields:[["key","Setting key","text",true],["value","Value","textarea",true],["description","Internal description","text"]]},
};
export function getContentType(type){return contentTypes[type]||null;}
