import { buildMetadata } from "@/lib/metadata";

export const metadata = buildMetadata({
  title: "Backyard Zoning Case Study | Orlano Gardens",
  description: "A detailed digital design case study showing how outdoor rooms were added without sacrificing the open backyard center.",
  path: "/projects/backyard-zoning-case-study"
});

const structuredData = {
  "@context":"https://schema.org",
  "@type":"Organization",
  "name":"Orlano Gardens",
  "url":"https://orlanogardens.com/projects/backyard-zoning-case-study",
  "email":"orlanogardens@gmail.com",
  "sameAs":["https://orlanogardens.etsy.com/","https://www.instagram.com/orlanogardens","https://www.facebook.com/orlanogardens"],
  "description":"Remote digital outdoor design created from client-supplied property photos."
};

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
      <main id="main-content">
      <section className="hero hero--dark"><div className="container hero__grid"><div><div className="eyebrow eyebrow--gold">Project case study 01 / Backyard zoning</div><h1>A backyard designed around <span className="accent">open space.</span></h1><p className="lead">The goal was not to fill the lawn. It was to create somewhere to sit, dine and move without sacrificing the flexible center.</p><ul className="check-list"><li>Protect the open lawn</li><li>Place activity near the house</li><li>Use the perimeter for planting and privacy</li></ul><div className="hero__proofs"><span className="chip">Remote service</span><span className="chip">Digital concept</span><span className="chip">No installation shown</span></div></div><div className="hero__visual"><span className="image-label">Digital Design Concept</span><img className="hero__image" src="/assets/images/backyard-second-view.webp" alt="Selected backyard digital design direction" /><div className="hero__caption"><strong>Two outdoor rooms. One protected center.</strong><span>Selected direction for the case study.</span></div></div></div></section>
      <section className="section section--tight"><div className="container"><div className="facts"><div className="fact"><small>Project type</small><strong>Backyard zoning</strong></div><div className="fact"><small>Primary goal</small><strong>Keep the lawn open</strong></div><div className="fact"><small>Design method</small><strong>Photo-based remote concept</strong></div><div className="fact"><small>Status</small><strong>Digital design case study</strong></div></div></div></section>
      <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">Original space to selected direction</div><h2>The yard had space. It had no destination.</h2></div><p>The concept adds function around the edges instead of consuming the center.</p></div><div className="comparison-card"><img src="/assets/images/backyard-before-after.webp" alt="Backyard original photo and digital design concept" /><div className="comparison-card__labels"><span>Original client photo</span><span>Digital Design Concept</span></div><div className="comparison-card__body"><h3>Honest presentation boundary</h3><p>The right image is a visual concept for planning. It is not a photograph of completed construction or installation.</p></div></div></div></section>
      <section className="section section--dark"><div className="container"><div className="section-heading"><div><div className="eyebrow">Visible constraints</div><h2>The design had to protect what already worked.</h2></div><p>The open center, house access and existing boundaries controlled the solution.</p></div><div className="grid grid--4"><article className="card card--dark"><span className="card__number">A</span><h3>Open center</h3><p>The middle remains available for play, pets and future flexibility.</p></article><article className="card card--dark"><span className="card__number">B</span><h3>House connection</h3><p>Dining remains near the door instead of being pushed to the far boundary.</p></article><article className="card card--dark"><span className="card__number">C</span><h3>Perimeter value</h3><p>Planting and privacy occupy the edges where they do not fragment use.</p></article><article className="card card--dark"><span className="card__number">D</span><h3>Clear passage</h3><p>Movement between door, lawn and activity zones stays obvious.</p></article></div></div></section>
      <section className="section section--ivory"><div className="container split"><div className="image-frame"><span className="image-label">Zone strategy</span><img src="/assets/images/backyard-zones.webp" alt="Backyard digital concept with activity zones" /></div><div><div className="eyebrow">The design decision</div><h2>Build around the center—not through it.</h2><p className="lead">The strongest move was to resist adding features to every available patch of lawn.</p><ul className="check-list"><li>Dining stays close to the house.</li><li>A secondary lounge creates a different use.</li><li>Planting frames rather than consumes the yard.</li><li>Circulation runs along clear, direct routes.</li></ul></div></div></section>
      <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">What the layout solves</div><h2>Each zone earns its place.</h2></div><p>Outdoor rooms are defined by use, connection and realistic movement—not decoration alone.</p></div><div className="grid grid--3"><article className="card"><span className="card__number">01</span><h3>Dining near service</h3><p>Food and furniture move through the nearest door without crossing the full yard.</p></article><article className="card"><span className="card__number">02</span><h3>Lounge away from traffic</h3><p>A quieter secondary zone gains identity without blocking the main route.</p></article><article className="card"><span className="card__number">03</span><h3>Perimeter planting</h3><p>Planting softens edges, supports privacy and protects open ground.</p></article></div></div></section>
      <section className="section section--sage"><div className="container split"><div><div className="eyebrow">What the client receives</div><h2>A direction that can be discussed and phased.</h2><p>Concepts support better choices; they do not replace construction drawings, engineering or contractor verification.</p><ul className="check-list"><li>Selected digital concept views</li><li>Plant and material direction</li><li>Zone and placement guidance</li><li>Simple setup and care notes</li></ul></div><div className="image-frame"><span className="image-label">Practical handoff</span><img src="/assets/images/backyard-deliverables.webp" alt="Backyard design handoff example" /></div></div></section>
      <section className="section"><div className="container split"><div><div className="eyebrow">What to verify locally</div><h2>The image is a planning tool—not a construction permit.</h2><p>Before physical work, verify property lines, utilities, drainage, structure, fire-feature clearances, local codes and product requirements with qualified local professionals.</p></div><div className="card card--gold"><h3>Case study status</h3><p>This page documents an AI-assisted digital design concept. It does not claim that Orlano Gardens installed the project or that the concept represents completed construction.</p></div></div></section>
      <section className="cta-band"><div className="container cta-band__inner"><div><div className="eyebrow eyebrow--gold">Ready when the space is</div><h2>See what your own backyard could become.</h2><p>Share clear photos and priorities so the correct scope can be confirmed before Etsy checkout.</p></div><a className="btn btn--gold" href="/get-custom-design">Get Your Custom Design</a></div></section>
      </main>
    </>
  );
}
