import {NextResponse} from "next/server";
import {ObjectId} from "mongodb";
import {getDb} from "@/lib/mongodb";
import {requireAdmin} from "@/lib/admin-session";
import {guides} from "@/lib/guides";
import {legacyToArticle} from "@/lib/article-normalize";
function fromLegacy(slug){const index=guides.findIndex(x=>x.slug===slug);return index<0?null:legacyToArticle(guides[index],index);}
export async function GET(_req,{params}){try{await requireAdmin();const {id}=await params;if(id.startsWith("legacy:")){const x=fromLegacy(id.slice(7));return x?NextResponse.json({id,...x,legacy:true}):NextResponse.json({error:"Not found"},{status:404});}const db=await getDb();const x=await db.collection("articles").findOne({_id:new ObjectId(id)});return x?NextResponse.json({id:String(x._id),...x,_id:undefined}):NextResponse.json({error:"Not found"},{status:404});}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
export async function PUT(req,{params}){try{const admin=await requireAdmin();const {id}=await params;const body=await req.json();const db=await getDb();const record={...body,slug:String(body.slug||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),featured:Boolean(body.featured),blocks:Array.isArray(body.blocks)?body.blocks:[],publishAt:body.publishAt?new Date(body.publishAt):null,updatedAt:new Date(),updatedBy:admin.email};delete record.id;delete record._id;delete record.legacy;if(record.featured)await db.collection("articles").updateMany({},{$set:{featured:false}});if(id.startsWith("legacy:")){const base=fromLegacy(id.slice(7));const result=await db.collection("articles").insertOne({...base,...record,createdAt:new Date()});return NextResponse.json({ok:true,id:String(result.insertedId)});}await db.collection("article_revisions").insertOne({articleId:new ObjectId(id),snapshot:await db.collection("articles").findOne({_id:new ObjectId(id)}),createdAt:new Date(),createdBy:admin.email});await db.collection("articles").updateOne({_id:new ObjectId(id)},{$set:record});return NextResponse.json({ok:true,id});}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
export async function DELETE(_req,{params}){try{await requireAdmin();const {id}=await params;if(id.startsWith("legacy:"))return NextResponse.json({error:"Migrate the built-in article before deleting it"},{status:400});const db=await getDb();await db.collection("articles").deleteOne({_id:new ObjectId(id)});return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e.message},{status:e.message==="UNAUTHORIZED"?401:500});}}
